### ISSUE TITLE
Error deleting a wiki page

### ISSUE THREAD

**Issue by rbonatuvic** [moodleou/moodle-mod_ouwiki#34]
With the 2014042800 version we received when deleting a wiki page:
error/Database problem: Error deleting/undeleting ouwiki page version exception 'dml_read_exception' with message 'Error reading from database' ...

This was the result of an Oracle error:
ORA-00918: column ambiguously defined

I was able to track this to an extra 'u.id' field left over when you switched to 'user_picture::fields' field assembly.
As of commit c79efd0207, the offending line was locallib.php 1293. There are 3 other places where this may be a problem or at least unnecessary code; locallib.php line 593, 600, 857.

**Comment by jason-platts** [comment]
This is (finally) fixed and will make it's way to master branch on our next push upstream.
