### ISSUE TITLE
Can not use template in zip form

### ISSUE THREAD

**Issue by heather-williams** [moodleou/moodle-mod_ouwiki#39]
I am using the latest 2.6 version of ouwiki. I create a wiki with pages and then download it as a template. I create a new wiki and then attach the zip file for the one I just downloaded to it and hit save settings and get the following error:

Not a zip archive.: /mnt/data/moodledata_prod/filedir/bf/03/bf0329150a250ed8d9dd534b96e3067b72a4f316

line 133 of /lib/filestorage/zip_archive.php: call to debugging()
line 399 of /lib/filestorage/zip_packer.php: call to zip_archive->open()
line 556 of /lib/filestorage/stored_file.php: call to zip_packer->extract_to_storage()
line 387 of /lib/filestorage/zip_packer.php: call to stored_file->extract_to_storage()
line 304 of /mod/ouwiki/locallib.php: call to zip_packer->extract_to_storage()
line 163 of /mod/ouwiki/locallib.php: call to ouwiki_init_pages()
line 77 of /mod/ouwiki/basicpage.php: call to ouwiki_get_subwiki()
line 29 of /mod/ouwiki/view.php: call to require()

If I unzip the file locally and use the .xml file, that works. However, it seems to me if it downloads in a .zip format, then you should be able to use it in the .zip format.

**Comment by heather-williams** [comment]
This issue will not let me attach a zip file. How would you like me to attach it?

**Comment by jason-platts** [comment]
Sorry, that's a problem then. Could you share in the 'Cloud' somewhere public like in Google drive?

**Comment by heather-williams** [comment]
Try this: https://drive.google.com/file/d/0BzfIJw-2dHFPWTgxd2ExN1Ixenc/view?usp=sharing

**Comment by jason-platts** [comment]
I get errors that the zip file is invalid when opening it in WinZip etc. Either the sharing has messed it up or it was invalid to start with?

**Comment by heather-williams** [comment]
That is how it is when you download it from the ouwiki. I was able to unzip it with 7zip.

**Comment by jason-platts** [comment]
Aha, thanks. Sounds like the zip creation is the issue rather than the importing.

**Comment by jason-platts** [comment]
I don't seem to be able to find any problems when creating a zip template. Any chance you could share the xml file if that worked and I can then try and create a zip after importing that (I'm assuming that you find that a zip template created from your imported xml template wiki is broken also)?

**Comment by heather-williams** [comment]
If I unzip it and use the xml it imports fine. But not when I use the zip file it creates. I was able to replicate this on multiple sites and other items that are exported in a zip file are fine, so I'm a bit confused about it. Are you saying in the 2014042800 version, that the exported zip file is fine for you when you test it?

**Comment by jason-platts** [comment]
No, the exported zip file is invalid and so doesn't work for me. If you have other wiki's that export as zip fine then there might be something specific to the wiki in question. If I had the xml file from that broken zip (or a moodle backup of the wiki with user data included) I could try and recreate your wiki and see if there are problems specific to it that I can pick up.

**Comment by heather-williams** [comment]
https://drive.google.com/file/d/0BzfIJw-2dHFPUnhDb3VmR3VET1U/view?usp=sharing

That should link you to the xml file from that zip file

**Comment by heather-williams** [comment]
Also, my question was if you have a test site where exporting in that version does give you a valid zip file?

**Comment by jason-platts** [comment]
Try implementing this patch...
https://github.com/moodleou/moodle-mod_ouwiki/commit/804867ad863ef0adff71c842ddd213c40991a100

I'd forgotten that we did have a post 2.6 version problem that was only fixed in master + 2.7 versions.
Perhaps you don't have debugging enabled so wouldn't spot the error.

It should hopefully fix the problem.

**Comment by heather-williams** [comment]
That did it! Thank you!

**Comment by jason-platts** [comment]
Excellent. Thank you for your patience!
