### ISSUE TITLE
Participation summary on user outline report not working/inconsistent with complete report

### ISSUE THREAD

**Issue by owenbarritt** [moodleou/moodle-mod_ouwiki#43]
When viewing a user's outline report it shows no details for ouwiki regardless of what the user has done.  The complete report does at least show number of views, which the outline report also shows for other resources/activities.

Looks like ouwiki_user_outline() is defined, but not returning anything.  Whereas ouwiki_user_complete() isn't defined, so presumably moodle resorts to a default behavior.

Perhaps the code from the user participation screen could be reused here to display something more useful?

**Comment by jason-platts** [comment]
Fixed - thanks for your patch.
