### ISSUE TITLE
Need information

### ISSUE THREAD

**Issue by atlantisUnity** [moodleou/moodle-mod_ouwiki#51]
Hello I am at present a trainee in computing and I work on OUwiki. I wanted to know how to get back the contents of a wiki with id of the page.

**Comment by jason-platts** [comment]
To get the latest text for a specified page:

In PHP: ouwiki_get_current_page() in locallib.php
In SQL: See the query in that function

**Comment by atlantisUnity** [comment]
Why  ouwiki_get_current_page() replaces the links of my images 
examples : http://moodle-dev.dinf.cll.qc.ca/pluginfile.php/45/mod_ouwiki/content/46/ch%20gene.jpg

and after : http://moodle-dev.dinf.cll.qc.ca/mod/ouwiki/@@PLUGINFILE@@/ch%20gene.jpg
