### ISSUE TITLE
mod_ouwiki: Content not processed/saved before or after time has elasped

### ISSUE THREAD

**Issue by kiratskitizing** [moodleou/moodle-mod_ouwiki#87]
Ouwiki
$plugin->version  = 2017101200;
$plugin->release = '3.1 r1';

Moodle
$version  = 2021052500.17;
$release  = '4.0dev (Build: 20200929)'

Steps to replicate:
1 Create acourse.
2 Click on “Turn editing on”
3 Click on “Add an activity or resource”
4 Select “OU wiki”
5 Enter a Name
6 Expand “Wiki settings”
7 Select a value for “Time allowed for edit” (“15 minutes” or “3 minutes (for testing)”)
8 Click on “Save and display”
9 Click on “Create page” 
10 Enter some content before the time elapses (timer is counting down)
11 Click on “Save changes”
12 Click on “Edit page”
13 Enter additional content before the time elapses (timer is counting down)
14 At 2 minute mark, message is displayed in red: “Please finish or cancel your edit now. If you do not save before time runs out, your changes will be saved automatically“
15 Let the timer reach 0.00
16 Click on “Save”

RESULT: The page is still created even if the timer reached 0.00

17. Repeat steps 3 to 15.
18. Click on "Cancel"

RESULT: The page does not save even if the timer reached 0.00

The text shows that 
> "This wiki allows only 3 minutes for editing. Make your changes and click Save or Cancel before the remaining time (to right) reaches zero.Please finish or cancel your edit now. If you do not save before time runs out, your changes will be saved automatically."

But looks like it does not save automatically.

**Comment by jason-platts** [comment]
Please update to the latest code version from this repo, this was fixed in:

https://github.com/moodleou/moodle-mod_ouwiki/commit/51060ced65cf51a8615bad587fcda296c341614c
