### ISSUE TITLE
Moodle 4.0 support?

### ISSUE THREAD

**Issue by paaskynen** [moodleou/moodle-mod_ouwiki#95]
Thanks for this useful plugin. What with Moodle 3 nearing the end of the road, will there be a Moodle 4 version of this plugin?

**Comment by sammarshallou** [comment]
Our plugins have been updated to work on Moodle 4 (we are live with 4.0.something since December), but we had neglected to run the script to update GitHub, apologies. I've run it now, so the MOODLE_400_STABLE branch should now exist (along with a final update to MOODLE_311_STABLE).
